[general]
title = "Example 01"
opening_msg = "これは目隠し双六の例です。"
start_description = "学校を目指そう！！\nスタート！！"
goal_description = "ゴール！！ 無事、学校に到着！！\nおめでとう！！"
dice_max = 4

[[area]]
description = "靴紐が切れた。"
[[area.effect]]
name = "SkipSelf"
settings = "2"

[[area]]
description = "1時間に1本のバスに間に合った。"
[[area.effect]]
name = "AdvanceSelf"
settings = "2"

[[area]]
description = "天気が良くて気持ちが良い。"
[[area.effect]]
name = "NoEffect"
settings = ""

[[area]]
description = "川が綺麗だ。"
[[area.effect]]
name = "NoEffect"
settings = ""

[[area]]
description = "不審者発見。"
[[area.effect]]
name = "DisadvanceSelf"
settings = "1"

[[area]]
description = "あともうすこしで学校だ。"
[[area.effect]]
name = "NoEffect"
settings = "1"

[[area]]
description = "忘れ物を家に取りに行く。"
[[area.effect]]
name = "DisadvanceSelf"
settings = "2"
